services:
  backend:
    build: ./backend
    container_name: io_guard_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - io_guard_net
    volumes:
      - ./backend:/app
      - ./tests:/app/tests

  frontend:
    build: ./frontend
    container_name: io_guard_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - io_guard_net

networks:
  io_guard_net:
    driver: bridge
